# Generated by Django 4.1.5 on 2023-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Launc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=9)),
                ("establishment", models.CharField(max_length=20)),
                ("invoice", models.CharField(max_length=255)),
            ],
        ),
    ]
