# Generated by Django 4.1.5 on 2023-01-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="parcel",
            field=models.CharField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (9, "Nine"),
                    (10, "Ten"),
                    (11, "Eleven"),
                    (12, "Twelve"),
                ],
                max_length=2,
            ),
        ),
    ]
