# Generated by Django 4.1.5 on 2023-01-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Launch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=9)),
                ("establishment", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Launc",
        ),
    ]
