# Generated by Django 4.1.5 on 2023-01-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0002_alter_launch_parcel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="date_hour",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
