# Generated by Django 4.1.5 on 2023-01-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="creation_date",
            new_name="created_at",
        ),
    ]
