# Generated by Django 4.1.5 on 2023-01-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="user_id",
            new_name="user",
        ),
    ]
