# Generated by Django 4.1.5 on 2023-01-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="economic_consultance_id",
            new_name="economic_consultance",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="insurance_id",
            new_name="insurance",
        ),
    ]
