# Generated by Django 4.1.5 on 2023-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
        ("account", "0003_rename_user_id_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="insurance_id",
            field=models.ManyToManyField(
                blank=True, related_name="account", to="insurance.insurance"
            ),
        ),
    ]
