# Generated by Django 4.1.5 on 2023-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economicConsultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicconsultant',
            name='specialty',
            field=models.CharField(choices=[('Investimentos', 'Investimentos'), ('Finanças Pessoais', 'Financas Pessoais'), ('Poupança', 'Poupanca')], max_length=30),
        ),
    ]
