# Generated by Django 4.1.5 on 2023-01-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurance",
            name="name",
            field=models.CharField(default="vida", max_length=50),
            preserve_default=False,
        ),
    ]
