# Generated by Django 4.1.5 on 2023-01-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("card", "0002_rename_availablelimit_card_available_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(max_length=17)),
                ("month", models.CharField(max_length=20)),
                ("paid", models.BooleanField(default=False)),
                ("due_date", models.DateField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="card.card",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
