# Generated by Django 4.1.5 on 2023-01-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("launch", "0002_launch_delete_launc"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="launch",
            field=models.ManyToManyField(related_name="invoices", to="launch.launch"),
        ),
    ]
