# Generated by Django 4.1.5 on 2023-01-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="month_reference",
        ),
    ]
