# Generated by Django 4.1.5 on 2023-01-06 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice_launch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="month",
        ),
        migrations.AddField(
            model_name="invoice",
            name="closing_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="month_reference",
            field=models.DateField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
