# Generated by Django 4.1.5 on 2023-01-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=16)),
                ('password', models.IntegerField(max_length=4)),
                ('cvv', models.IntegerField(max_length=3)),
                ('currentValue', models.FloatField(max_length=17)),
                ('dueDate', models.IntegerField(max_length=2)),
                ('cardType', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='Debit', max_length=6)),
                ('totalLimit', models.FloatField(max_length=17)),
                ('availableLimit', models.FloatField(max_length=17)),
                ('cardExpiration', models.DateField()),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
