# Generated by Django 4.1.5 on 2023-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
