# Generated by Django 4.1.5 on 2023-01-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="availableLimit",
            new_name="available_limit",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="currentValue",
            new_name="balance_invoices",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="cardExpiration",
            new_name="due_card",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="isActive",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="totalLimit",
            new_name="total_limit",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cardType",
        ),
        migrations.RemoveField(
            model_name="card",
            name="dueDate",
        ),
        migrations.AddField(
            model_name="card",
            name="account_id",
            field=models.ForeignKey(
                default=999999,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card",
                to="account.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="card_expiration",
            field=models.DateField(auto_now_add=True, default="2040-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="due_date",
            field=models.CharField(
                choices=[
                    ("05", "First Option"),
                    ("15", "Second Option"),
                    ("29", "Third Option"),
                ],
                default="05",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[
                    ("Debit", "Debit"),
                    ("Credit", "Credit"),
                    ("Múltiplo", "Both"),
                ],
                default="Debit",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="cvv",
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="card",
            name="number",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="card",
            name="password",
            field=models.CharField(max_length=4),
        ),
    ]
