# Generated by Django 4.1.5 on 2023-01-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="account_id",
            new_name="account",
        ),
    ]
