# Generated by Django 4.1.5 on 2023-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_rename_availablelimit_card_available_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="card_expiration",
        ),
        migrations.AlterField(
            model_name="card",
            name="cvv",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="card",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
