# Generated by Django 4.1.5 on 2023-01-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_alter_card_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="due_date",
            field=models.CharField(
                choices=[
                    ("06", "First Option"),
                    ("19", "Second Option"),
                    ("28", "Third Option"),
                ],
                default="06",
                max_length=8,
            ),
        ),
    ]
