# Generated by Django 4.1.5 on 2023-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_rename_account_id_card_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="due_card",
            field=models.CharField(max_length=8),
        ),
    ]
