# Generated by Django 4.1.5 on 2023-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_alter_card_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="cvv",
            field=models.CharField(max_length=128),
        ),
    ]
