# Generated by Django 4.1.5 on 2023-01-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0003_remove_card_card_expiration_alter_card_cvv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="balance_invoices",
            field=models.CharField(max_length=17),
        ),
    ]
