# Generated by Django 4.1.5 on 2023-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0004_alter_card_balance_invoices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="balance_invoices",
            field=models.FloatField(max_length=17),
        ),
    ]
