# Generated by Django 4.1.5 on 2023-01-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentCdi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initial_value", models.DecimalField(decimal_places=2, max_digits=17)),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=17)),
                ("yield_value", models.DecimalField(decimal_places=2, max_digits=17)),
                ("creation_date", models.DateField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investmentsCdi",
                        to="account.account",
                    ),
                ),
            ],
        ),
    ]
