# Generated by Django 4.1.5 on 2023-01-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InvestmentCdi", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investmentcdi",
            old_name="account",
            new_name="account_id",
        ),
    ]
