# Generated by Django 4.1.5 on 2023-01-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InvestmentCdi", "0003_rename_account_investmentcdi_account_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investmentcdi",
            old_name="account_id",
            new_name="account",
        ),
    ]
