# Generated by Django 4.1.5 on 2023-01-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousBalance', models.FloatField(max_length=17)),
                ('currentBalance', models.FloatField(max_length=17)),
                ('operation', models.CharField(max_length=50)),
                ('creatadAt', models.DateTimeField()),
            ],
        ),
    ]
