# Generated by Django 4.1.5 on 2023-01-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valueOperation", models.FloatField(default=0.1, max_length=17)),
                ("previous_balance", models.FloatField(max_length=17)),
                ("current_balance", models.FloatField(max_length=17)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("transferência", "Transferência"),
                            ("saque", "Saque"),
                            ("pagamento", "Pagamento"),
                            ("depósito", "Depósito"),
                        ],
                        max_length=13,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extract",
                        to="account.account",
                    ),
                ),
            ],
        ),
    ]
