# Generated by Django 4.1.5 on 2023-01-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extract", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extract",
            old_name="creatadAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="extract",
            old_name="currentBalance",
            new_name="current_balance",
        ),
        migrations.RenameField(
            model_name="extract",
            old_name="previousBalance",
            new_name="previous_balance",
        ),
    ]
