# Generated by Django 4.1.5 on 2023-01-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("extract", "0002_rename_creatadat_extract_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extract",
            name="account",
            field=models.ForeignKey(
                default=999999,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extract",
                to="account.account",
            ),
            preserve_default=False,
        ),
    ]
