# Generated by Django 4.1.5 on 2023-01-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extract", "0003_extract_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="extract",
            name="type",
            field=models.CharField(
                choices=[
                    ("TED", "Ted"),
                    ("PIX", "Pix"),
                    ("BOLETO", "Boleto"),
                    ("NÃO IFORMADO", "Erro"),
                ],
                default="NÃO IFORMADO",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="extract",
            name="valueOperation",
            field=models.FloatField(default=0.1, max_length=17),
        ),
        migrations.AlterField(
            model_name="extract",
            name="operation",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("RETIRADA", "Retirada"),
                    ("NÃO EFETUADO", "Erro"),
                ],
                default="NÃO EFETUADO",
                max_length=12,
            ),
        ),
    ]
